britsamazeballsrepo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'arenas#index'

  resources :arenas
  resources :gladiators

end

britsamazeballsrepo/app/models/arena.rb
class Arena < ActiveRecord::Base
  has_many :gladiators
end

britsamazeballsrepo/app/models/concerns/gladiator.rb
class Gladiator < ActiveRecord::Base
  belongs_to :arena
end

britsamazeballsrepo/app/models/gladiator.rb
class Gladiator < ActiveRecord::Base
  belongs_to :arena
end

britsamazeballsrepo/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

britsamazeballsrepo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

britsamazeballsrepo/app/controllers/arenas_controller.rb
class ArenasController < ApplicationController
  before_action :authenticate_user!
  def index
    @arenas = Arena.all
  end

  def show
    @arena = Arena.find(params[:id])
  end



end

britsamazeballsrepo/app/controllers/gladiators_controller.rb
class GladiatorsController < ApplicationController

  def index
    @gladiators = Gladiator.all
  end

  def show
    @gladiator = Gladiator.find(params[:id])
  end

end

britsamazeballsrepo/app/helpers/application_helper.rb
module ApplicationHelper
end

britsamazeballsrepo/app/views/arenas/index.html.erb
<h1>The Arenas</h1>

<% @arenas.each do |arena| %>
  <div class='arena'>
    <h2><%=link_to arena.name, arena_path(arena)%></h2>

  </div>
<% end %>

britsamazeballsrepo/app/views/arenas/show.html.erb
<h1><%= @arena.name %></h1>
<% @arena.gladiators.each do |gladiator| %>
<div class="gladiator">
  <h2><%= gladiator.name %></h2>
  <%=image_tag gladiator.img_url %>
</div>
<% end %>

britsamazeballsrepo/app/views/gladiators/index.html.erb
<h1>Gladiators CAN FIGHT!</h1>
<% @gladiators.each do |gladiator| %>
  <div>
    <%= link_to gladiator.name,  gladiator_path(gladiator) %> - <%= gladiator.arena.name %>
<% end %>
  </div>

britsamazeballsrepo/app/views/gladiators/new.html.erb
<h1>Welcome to Gladiator Hell</h1>
<% img_tag "" %>

britsamazeballsrepo/app/views/gladiators/show.html.erb
<h1><%= @gladiator.name %></h1>
<h2><%= @gladiator.house.name %></h2>
<div class="gladiator">
  <%= image_tag @gladiator.img_url %>
</div>

britsamazeballsrepo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Britsamazeballsrepo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>